#!/bin/bash
###############################################################################
#   This file is part of map_gen, an external random map generator for C-Evo
#   Copyright (C) 2017  Ulrich Krueger
#
#   Map_gen is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Map_gen is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with map_gen.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################
# build  cpp                                                       2017-Feb-27
#=============================================================================

#==========  function definitions  ============================================

#------------------------------------------------------------------------------
   # Does a cleanup (if necessary) and exits; param $1 is the exit code
function build_exit ()
{
 	echo This was a warning 
}


#==========  start of program flow  ===========================================

#==========  set some variables  ==============================================

CC_OPTIONS="-Wall -Wno-main"

CC_PATHES="-I ../include -L ../lib"

SRC="cpp_main.c cpp_getc.c inc_stk.c mac_tab.c"


#==========  compile the program  =============================================

#cc ${CC_OPTIONS} ${CC_PATHES} -DDEBUG ${SRC} -l_misc -o cpp || build_exit 1
#cc ${CC_OPTIONS} ${CC_PATHES} ${SRC} -l_misc -o cpp || build_exit 1
gcc -Os ${CC_OPTIONS} ${CC_PATHES} ${SRC} -l_misc -o cpp || build_exit 1


#=============================================================================
echo cpp built successfully
build_exit 0
