#!/bin/bash
###############################################################################
#   This file is part of map_gen, an external random map generator for C-Evo
#   Copyright (C) 2017  Ulrich Krueger
#
#   Map_gen is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Map_gen is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with map_gen.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################
# build  map_gen                                                   2017-Mar-27
#=============================================================================

#==========  function definitions  ============================================

#------------------------------------------------------------------------------
   # Does a cleanup (if necessary) and exits; param $1 is the exit code
function build_exit ()
{
  exit $1
}


#==========  start of program flow  ===========================================

#==========  set some variables  ==============================================

CC_OPTIONS="-Wall -Werror"
CC_PATHES="-I ../include -L ../lib"

SCENARIOS=scn_*.c
LANDSCAPE_ELEMENTS=aux_*.c

FILES="map_gen.c read_ini.c ${SCENARIOS} ${LANDSCAPE_ELEMENTS}"
LIBS="../cevo_lib/lib_cevo.a -lm -l_scan -l_misc"


#==========  compile the program  =============================================

gcc -Os ${CC_OPTIONS} ${CC_PATHES} ${FILES} ${LIBS} -o map_gen || build_exit 1


#=============================================================================
echo map_gen built successfully
build_exit 0
