#!/bin/bash
###############################################################################
#   This file is part of map_gen, an external random map generator for C-Evo
#   Copyright (C) 2017  Ulrich Krueger
#
#   Map_gen is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Map_gen is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with map_gen.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################
# build_ri    build include files for read_ini                      2017-Mar-05
#==============================================================================

#==========  function definitions  ============================================

#------------------------------------------------------------------------------
   # Does a cleanup (if necessary) and exits; param $1 is the exit code
function build_exit ()
{
  exit $1
}


#==========  start of program flow  ===========================================

#==========  set some variables  ==============================================

CPP_CMD=../../cpp/cpp

   # check for existence
if test ! -x ${CPP_CMD} ; then
  echo "building .i files: cannot find cpp"
  build_exit 3
fi

#==========  preprocess to generate the .i files  =============================

${CPP_CMD} extern.c || build_exit 1
${CPP_CMD} globals.c || build_exit 1
${CPP_CMD} table.c || build_exit 1

mv extern.i .. || build_exit 2
mv globals.i .. || build_exit 2
mv table.i .. || build_exit 2


#==============================================================================
echo include files for read_ini built successfully
build_exit 0
